# Generated by Django 4.0.3 on 2022-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(default='', max_length=200)),
                ('weight', models.FloatField()),
                ('destination', models.CharField(default='', max_length=250)),
                ('description', models.CharField(default='', max_length=500)),
                ('ship_date', models.DateField()),
            ],
        ),
    ]
