# Generated by Django 4.0.3 on 2022-03-26 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(default='', max_length=250)),
                ('contact', models.CharField(default='', max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='cargo',
            new_name='cargo_text',
        ),
        migrations.AddField(
            model_name='shipment',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='api.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shippingcompany'),
        ),
    ]
