# Generated by Django 4.0.3 on 2022-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shippingcompany_rename_cargo_shipment_cargo_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
