# Generated by Django 4.0.3 on 2022-03-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220326_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipping_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='api.shippingcompany'),
        ),
    ]
