# Generated by Django 4.0.3 on 2022-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shipment_shipping_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
