# Generated by Django 4.0.3 on 2022-03-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_shippingcompany_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='cargo_text',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
    ]
