# Generated by Django 4.0.3 on 2022-03-27 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_shipment_cargo_text_remove_shipment_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to='api.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='contact_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
