# Generated by Django 4.0.3 on 2022-03-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cargo_shipment_alter_shipment_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='api.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='contact',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='office',
            field=models.CharField(max_length=250),
        ),
    ]
