# Generated by Django 4.0.3 on 2022-03-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cargo_name_alter_cargo_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargoes', to='api.shipment'),
        ),
    ]
