# Generated by Django 4.0.3 on 2022-03-27 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_cargo_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='volume',
            field=models.FloatField(verbose_name='Cargo vulume, cubic m'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.FloatField(verbose_name='Cargo weight, kg'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='contact_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name="Recipient's phone"),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=250, verbose_name='Destination address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(max_length=250, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_date',
            field=models.DateField(verbose_name='Shipment date'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='contact',
            field=models.CharField(max_length=250, verbose_name='Contact person'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='office',
            field=models.CharField(max_length=250, verbose_name='Office address'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Format:'+XXX'. Up to 15 digits.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Office phone number'),
        ),
    ]
