# Generated by Django 4.0.3 on 2022-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_cargo_volume_alter_cargo_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='volume',
            field=models.FloatField(verbose_name='Cargo volume, cubic m'),
        ),
    ]
